config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :albums
  post 'find_album'=> "home#find_album", :as => "find_album"
  resources :homes

end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :images, :dependent => :destroy
	accepts_nested_attributes_for :images, :reject_if => lambda { |a| a[:photo].blank? }
	validates_presence_of :name
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :album
	belongs_to :user
	has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => '/noImage.png'
  	validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  	 validate :maximum_uplaod

  	def maximum_uplaod
  		find_image = Image.where("album_id = ?", album_id)
  		unless find_image.length < 25
  			errors.add("can not", "be uploaded more than 25 per Album.")
  		end

  	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :image
  validates_format_of :email, :with => /\A[\w][A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_filter :require_login, :only => [:index, :new, :edit, :show]
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
    @image = @album.images.build
    @user = User.all
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
    @image = @album.images.build
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)
    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :user_id, images_attributes: [:id,:photo, :user_id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def require_login
  	unless logged_in?
  		redirect_to new_user_session_path
  	end
  end

  def logged_in?
  	!!current_user
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@images = Image.order("id DESC").limit(25)
	end

	def find_album
		@find_album = Album.where("name LIKE ?", "%#{params[:album_name]}%")
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_form.html.erb
<%= form_for @album, :html => { :class => "form-horizontal album" } do |f| %>

    <% if @album.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @album.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
      <%= f.hidden_field :user_id, :value => current_user.id, :class => 'form-control' %>
    </div>
    <%= error_span(@album[:name]) %>
  </div>
  <div class="control-group">
    <%= f.fields_for :images do |ph| %>
      <br>
      <div class="controls">
        <div style = "width: 50%;float:left;">
          <%= ph.file_field :photo, :class => 'control-label' %>
          <%= ph.hidden_field :user_id, :value => current_user.id %>
        </div>
        <div>
          <%= image_tag ph.object.photo.url(:thumb) %>
        </div>
      </div>
    <%end%>
    <%= error_span(@album[:user_id]) %>
  </div>

  <br><br>
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            albums_path, :class => 'btn btn-default' %>

<% end %>

app/views/albums/edit.html.erb
<%- model_class = Album -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/albums/index.html.erb
<%- model_class = Album -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @albums.each do |album| %>
      <% if album.user_id == current_user.id %>
        <tr>
          <td><%= album.name %></td>
          <td><%= album.user_id %></td>
          <td><%=l album.created_at %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_album_path(album), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        album_path(album),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <%end%>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_album_path,
            :class => 'btn btn-primary' %>

app/views/albums/new.html.erb
<%- model_class = Album -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/albums/show.html.erb
<%- model_class = Album -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @album.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @album.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              albums_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_album_path(@album), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              album_path(@album),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/home/find_album.html.erb
<div class = "main-page">
	<div class = "search-form" style = "width: 82%;">
		<%= form_tag  find_album_path, :method => :post  do %>
			<%= text_field_tag :album_name %>
			<%= submit_tag "Submit",:class=>'btn btn-primary'%>
		<%end%>
	</div>
	<div class = "search-album-url">
		<%= link_to "Home", root_path,:class=>'btn btn-primary', :id => "search-submit" %><br>
	</div>
</div>
<div style = "margin-left:70px">
	<div class= "last_images" style = "float: left;">
		<% @find_album.each do |album| %>
			<h3><%= album.name %></h3>
			<%album.images.each do |image|%>
				<div class= "last_images" style = "float: left;width: 16%;">
					<%= image_tag image.photo.url(:thumb), :width => "150px", :height => "100px" %>
					<h4><%= image.user.username %></h4>
				</div>
			<%end%>
			<div style = "clear: both;"></div>
		<%end%>
	</div>
</div>

app/views/home/index.html.erb
<div class = "main-page">
	<div class = "search-form">
		<%= form_tag  find_album_path, :method => :post  do %>
			<%= text_field_tag :album_name %>
			<%= submit_tag "Submit",:class=>'btn btn-primary'%>
		<%end%>
	</div>
	<div class = "search-album-url">
		<%= link_to "Create/List Album", albums_path,:class=>'btn btn-primary', :id => "search-submit" %><br>
	</div>
</div>
<div style = "margin-left:70px">
	<% @images.each do |image|%>
		<div class= "last_images" style = "float: left;width: 16%;">
			<%= image_tag image.photo.url(:thumb), :width => "150px", :height => "100px" %>
			<h4><%= image.user.username %></h4>
		</div>
	<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageShare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>
    <div class = "after-signin">
      Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete,:class=>'btn btn-primary' %>
      <%= link_to "Home", root_url,:class=>'btn btn-primary'%>
    </div>
  <% else %>
    <div class = "before-signin">
      <%= link_to "Sign up", new_user_registration_path,:class=>'btn btn-primary' %> or
      <%= link_to "Sign in", new_user_session_path,:class=>'btn btn-primary' %>
    </div>
  <% end %>
</div>
<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>
  </div>
</div>

</body>
</html>